"""Add applied_role and status to candidates

Revision ID: c17d8560e156
Revises: b06c9450d045
Create Date: 2026-06-24 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17d8560e156'
down_revision: Union[str, Sequence[str], None] = 'b06c9450d045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_context().bind
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('candidates')]
    
    if 'applied_role' not in columns:
        op.add_column('candidates', sa.Column('applied_role', sa.String(), nullable=True))
    if 'status' not in columns:
        op.add_column('candidates', sa.Column('status', sa.String(), server_default='Pending', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'status')
    op.drop_column('candidates', 'applied_role')
    # ### end Alembic commands ###
